= Production processing

== Automatic annotation of a corpus

The AS-D text-mining pipeline automatically extracts the following entities:

* Genes
* Markers
* Wheat phenotypes
* Wheat-related species (taxa)

All configuration files, AlvisNLP workflow plans, scripts, and resources used to create the AS-D text-mining pipeline are provided in the uc-tdm-AS-D repository in the openminted github (https://github.com/openminted/uc-tdm-AS-D). Documentation for running the pipeline to annotate and index a corpus is also included in the repository.

== Integration into a parent application

The text-mining annotations have been integrated into the parent application WheatIS enabling a researcher to search for Wheat-related entities and inspect occurences of text-mining annotations as well as results from other genomic databases, indexed by WheatIS.

Moreover, the same annotations are indexed by the semantic search engine of the first release and can be accessed directly, through the search interface available at http://bibliome.jouy.inra.fr/demo/wheat/alvisir/webapi/search?.


Detailed documentation, including a tutorial guiding the user on the interface can be found in the <<parent-application#, WheatIS documentation>>.

Detailed documentation on how to use the search engine can be found in the <<web_app_doc.adoc#, AS-D web application documentation>>.


